function count(n, array) {
  return array.reduce(function (acc, item) {
    if (item === n) {
      acc = acc + 1;
    }
    return acc;
  }, 0);
}

/*
 *function steadyGene(gene) {
 *  const tmp = gene.split('');
 *  //console.log(tmp);
 *  const genes = ['A', 'C', 'T', 'G'];
 *  const n = gene.length;
 *  const steadyLength = n / 4;
 *  let steadyGene = [];
 *  let toIncrease = [];
 *
 *  for (let i = 0; i < genes.length; i = i + 1) {
 *    const geneCount = count(genes[i], tmp);
 *    console.log(genes[i], geneCount);
 *    if (geneCount !== steadyLength) {
 *      //console.log('elaborate');
 *      if (geneCount > steadyLength) {
 *        const diff = geneCount - steadyLength;
 *        console.log(`decrease by ${diff}`);
 *      } else {
 *        const diff = steadyLength - geneCount;
 *        console.log(`increase by ${diff}`);
 *        for (let j = 0; j < diff; j = j + 1) {
 *          toIncrease.push(gene[i]);
 *        }
 *      }
 *    }
 *  }
 *  console.log(toIncrease.length);
 *
 *  return steadyGene;
 *}
 */

function steadyGene(gene) {
  const arr = gene.split('');
  const n = gene.length / 4;
  const geneStructure = {
    a: count('A', arr),
    c: count('C', arr),
    t: count('T', arr),
    g: count('G', arr),
  };

  let result = 0;
  let genes = ['a', 'c', 't', 'g'];
  //for (let letter in geneStructure) {
  for (let i = 0; i < genes.length; i = i + 1) {
    if (geneStructure[genes[i]] < n) {
      let diff = n - geneStructure[genes[i]];
      //console.log(genes[i], diff);
      result = result + diff;
    }
  }
  return result;
}

function test(fn, arg, expected) {
  let res = fn(arg) === expected;
  return res;
}

function main() {
  console.log(test(steadyGene, 'GAAATAAA', 5));
  console.log(test(steadyGene, 'TGATGCCGTCCCCTCAACTTGAGTGCTCCTAATGCGTTGC', 5));
  console.log(
    test(
      steadyGene,
      'ACAAAAATAAACAAAAACAAAAAAAAAATAAATACAATAAAAAAAAAAAATGAAATACAACAACAAATAAAATAAAAACGACTAAAAAATAAAAAAAAAAAAAAAAAGAGTACTAAAAAAAAAAAAAAAAAATAAAAAAAAAAAAAACACAATCAAAATAAACAAAAAAAAAAAAACCAAAATAATCAACAAAAAAAAAAAAAACAAAAACAACAACAAACAAAAAAAAACACAAACAAAAAAAAAAAAAAAACAAAACAAACAAAAAAAAAAAAACAAAAAAACAAAAAAAAAAAAAAAAACAAAAAAAAAAATAAAAAAAAAAAAAAAAAAAAAACAAACAAAAAAAAAAAATACAAAAAGCTATAAAAAAAAAAAAATTAAAAAACAAAAAAAAATAAAAAAAAAAAAAAAAAAAAAAAATAAAAAAAAAAAAAAAAAAAAAATAAAAAAAAAAAAAAAAAAGAAAAACAAAAAAAAAAAAAAAAACAACCAAAAAACAAAAAAAAACTAAAAAAAAAAAAAAAAAAAAAAAAAAATAACAAAAAACACAAAAAAAAAAAAGAAAGAAAAAAAACACAAAAAAAAACAAACAAAAAAAAAAAAAAAAAAAGAAAACAAAAAAACAAAAAAAACAAAAAAAAAACAAAAATTGGACAAAAAAAAACAAAAAAAAAAAACAAAAAAAGTAAAACAAATAAAAAAACAAAAAAAACAAAAAAAAAAAAAAAAAACAAAAAAGAAACAAAAAACAAAAAAAAATAACAAAACCAAAAAACAAATAAAAAACAAAAAAAATAACACAAAAAAAAAAAGAAACAAAAAAAAAAAAAAAAAAAAAAATTATAAAAAAAAAAAAAAAACAAAAAAAAAAAAAACAAAAAAAAAAGGAAAAAAAAAAAAAAAAAAAAAAAAAAATAACTAAACAAAAAAAAACAAACAAAAAATCAAAAAAAAAAAAGAAAAAAGAATAAGCAACAAAAACACAAAAAAAAAAAAAAAAAAAAAAAACATAAACAATAATAAAAAAAAAACAAAAAAAACAAAAGAACAACAAAAAACAAAACTAAACAAATAAAAAAAAAAAAACAAAAACTACAAAAAAAAAAAGAAAAAAAAAGAAAAAAAAACAAATAAAAGAAAAAAAAAAAAAAAAAAAACACAAAAAAAAAAATAAAAAAAAAAAAAAAAACAAAATAAACAAAAACAAAGAAAAAAACAAACAAAAAAAAAAAACAAAAAACTAAAAACAAAAAAAAAACAAAACACAAAAAAAAAAAAAAATAAAAAAAAAACAAAAAAACAAAAAGGAAAAAAAAAAAAGAACAAAAAAAAAAACAACAGAAAAAAGAAAAGAAAAAAAAAAAAAGACCACAAAATAAAAAAAAACAACAAACAAAAAAAAACAAAACAAAAAAACGAACAAAAAAAACAAAAACAAAAAAAAAAAAAAAAAAAAAAAGGCAAAAACAAAAAAAACAAAACAAAACAAAAAAACAAAAAAAAATTAAGATAAAGAACAAAAAAAGAAGAGAAAAAATTAACAAAAAAAAAAAAATAAAAAATACAAAAAGAAATAAAAAATACAACACACAACAAAAACGAAAAAAAAAAAAAAAACACAAAATAGAAAAAAAAAAAAAACAAAAAAAAAAAAAAGAAAAAAACAAAAAAAAAAAAATAAAAAAAAACGACACAGAAACAAAAAATAACAAAAAAAAAAAAAATAAAAAAAAAACAAAAAAAAAACAAAAAATAAAAAAAAAAACAAACAAAAAAAAAAAAAAAATAAAAAAAAAAAAAGCAAAACATAAACAAGAAAAAAAAAAAAAGTACAAATAACAAAACAAAAAAGACACTAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAACCACAAAACAAAAAAATAAAGCAAAAAAAAAAAAAAAAAAAAAAAAAAAATAAATGAAAAAAAAAAGAAAACCAAAAAAATAAAAGA',
      1393
    )
  );
}

main();
